config/routes.rb
TicketwebApp::Application.routes.draw do

	root :to => 'events#index'	

	resources :events

end

app/models/attraction.rb
class Attraction < ActiveRecord::Base
  attr_accessible :image, :video, :artist, :artistid, :billing, :links, :sequence, :genre
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :videoembed, :eventid, :additionallistingtext, :attractionList, :dates, :description, :eventimages, :eventname, :eventurl, :facebookeventid, :prices, :status, :tags, :venueid, :venue

	serialize :dates, JSON
	serialize :attractionList, JSON
	serialize :attractions, JSON

	def after_initialize
		self.attractions = []
	end

	def eventid=(value)
		self.id = value
	end

	def eventid
		self.id
	end

	def venue=(value)
		self.venueid = value["venueid"]
		existing_venue = Venue.find_by_id(self.venueid)
		if existing_venue == nil
			new_venue = Venue.new(value)
			new_venue.save
		else
			existing_venue.update_attributes(value)
		end
	end

	def venue
		Venue.find_by_id(self.venueid)
	end

	def attractionList=(value)
		if attractions == nil
			self.attractions = []
		end
		value.each do |v|
			new_attraction = Attraction.new(v)
			new_attraction.save
			self.attractions[new_attraction["sequence"]] = new_attraction.id
		end
	end

	def attractionList
		returned_list = []
		self.attractions.each do |a|
			loaded_attraction = Attraction.find_by_id(a)
			returned_list[loaded_attraction["sequence"]] = loaded_attraction
		end
		returned_list
	end

	private

		attr_accessible :attractions
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  attr_accessible :venueid, :address, :city, :country, :name, :postalcode, :state, :twitterid, :venueimages, :venueurl

	serialize :venueimages, JSON

	def venueid=(value)
		self.id = value
	end

	def venueid
		self.id
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def show
		@event = Event.find(params[:id])
	end

	def index
		@events = Event.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<%= provide(:title, 'All Events') %>
<h1>All Events</h1>

<ul>
	<% @events.each do |event| %>
		<li>
			<%= link_to event.eventname, event %>
		</li>
	<% end %>
</ul

app/views/events/show.html.erb
<% provide(:title, @event.eventname) %>
<%= link_to "Back to Events index", events_path %>
<h1><%= @event.eventname %></h1>
<h2><%= @event.dates["startdate"] %> -> <%= Time.at(Integer(@event.dates["enddate"])) %></h2>
<h3><%= link_to "Event Link", @event.eventurl %></h3>
<p>
<%= raw(@event.description) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketwebApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>